site_name: WSPR Analytics
site_description: Big Data utilities for WSPR DataSets

theme:
    name: 'material'
    features:
      - navigation.tabs

repo_name: KI7MT/wspr-analytics
repo_url: https://github.com/KI7MT/wspr-analytics
edit_uri: ""
copyright: Copyright &copy; 2016 - 2020 Greg Beam

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup:
    - Overview: 'tools/overview.md'
    - Install Python: 'tools/install-python.md'
    - Install Golang: 'tools/install-golang.md'
    - Install Sdkman: 'tools/install-sdkman.md'
    - Install Java: 'tools/install-java.md'
    - Install Spark: 'tools/install-spark.md'
    - Install Scala: 'tools/install-scala.md'
    - Install PostgreSQL: 'tools/install-postgresql.md'
    - Install ClickHouse: 'tools/install-clickhouse.md'
    - Install Grafana: 'tools/install-grafana.md'
    - Install VirtualBox: 'tools/install-virtualbox.md'
    - Install Vagrant: 'tools/install-vagrant.md'
  - Spark:
    - Overview: 'spark/overview.md'
    - Convert To Parquet: 'spark/convert-csv-parquet.md'
    - Query With Parquet: 'spark/query-with-parquet.md'
    - Top Ten Reporters: 'spark/top-ten-reporters.md'
    - Epoch Conversion: 'spark/epoch-conversion.md'
  - PySpark:
    - Overview: 'pyspark/overview.md'
    - Basic Examples: 'pyspark/basic-examples.md'
  - Jupyter:
    - Overview: 'notebooks/overview.md'
  - WSPR-Daemon:
    - Overview: 'wsprdaemon/overview.md'
    - Database Notes: 'wsprdaemon/database-notes.md'
