site_name: WSPR Analytics
site_description: Big Data utilities for WSPR DataSets

theme:
    name: 'material'
    features:
      - navigation.tabs

repo_name: KI7MT/wspr-analytics
repo_url: https://github.com/KI7MT/wspr-analytics
edit_uri: ""
copyright: Copyright &copy; 2016 - 2020 Greg Beam

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.tabbed
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup:
    - Overview: 'setup/overview.md'
    - Installing Python: 'setup/install-python.md'
    - Installing Java: 'setup/install-java.md'
    - Installing Sdkman: 'setup/install-sdkman.md'
    - Installing Scala: 'setup/install-scala.md'
    - Installing R-Tools: 'setup/install-r.md'
    - Installing Graphana: 'setup/install-grafana.md'
    - Installing PostgreSQL: 'setup/install-postgresql.md'
  - PySpark:
    - Overview: 'pyspark/overview.md'
    - Basic Examples: 'pyspark/basic-examples.md'
  - Scala:
    - Overview: 'scala/overview.md'
    - Convert To Parquet: 'scala/convert-csv-parquet.md'
    - Query With Parquet: 'scala/query-with-parquet.md'
    - Top Ten Reporters: 'scala/top-ten-reporters.md'
    - Spark Examples: 'scala/spark-examples.md'
  - R-Scripts:
    - Overview: 'rscripts/overview.md'
  - Jupyter:
    - Overview: 'notebooks/overview.md'
  - WSPR-Daemon:
    - Overview: 'wsprdaemon/overview.md'
